### ISSUE TITLE
About the requirements of  erfnet_pytorch_ros

### ISSUE THREAD

**Issue by heheguoqushi** [iandouglas96/erfnet_pytorch_ros#1]
Hello, i want to map semantics in Asoom, so i need erfnet_pytorch_ros as your introduction.  I find that  erfnet_pytorch need these requirements:
1.Python 3.6    2.Pytorch version for Python 3.6 with CUDA support (code only tested for CUDA 8.0). 
3.Additional Python packages
I want to ask if you have tried other version of Python and cuda to run erfnet_pytorch_ros? Thank you.

**Comment by iandouglas96** [comment]
Chances are that it will work fine for a fairly recent pytorch version (say at least 1.5 or something like that).  As long as the cuda version is sufficiently high for the pytorch version you are using, it should be fine.  So basically if you are running ubuntu 18.04 or later and install the torch available in pip I wouldn't expect problems.
