### ISSUE TITLE
Resource not found.

### ISSUE THREAD

**Issue by Vasu-Eng** [iandouglas96/erfnet_pytorch_ros#3]
![Screenshot from 2023-05-31 15-19-54](https://github.com/iandouglas96/erfnet_pytorch_ros/assets/76465619/d6203957-e478-459d-a135-0fc414214905)
Unable to find semantics_manager.
Please help resolve this.

**Comment by iandouglas96** [comment]
Use commit 2391550 (https://github.com/iandouglas96/erfnet_pytorch_ros/tree/23915508b9262f9c4450e11b3e0b7e6840c5df66)
